Lisää verifiointi steppi ECS deploylle
aws-actions/amazon-ecs-deploy-task-definition@v2 ei osaa failata
jos ECS deploy rolbackaa

diff --git a/.github/workflows/deploy_koski.yml b/.github/workflows/deploy_koski.yml
--- a/.github/workflows/deploy_koski.yml
+++ b/.github/workflows/deploy_koski.yml
@@ -57,12 +57,13 @@ jobs:
           image: ${{ steps.login-deployment.outputs.registry }}/koski:${{ inputs.commithash }}
 
       - name: Get AppSpec template
-        if: inputs.environment == 'prod'
+        if: inputs.environment == 'prod' #TODO remove this step when luovutuspalvelu v2 infra is deployed
         run: |
           aws ssm get-parameter --name /koski/appspec-template --output text --query 'Parameter.Value' > appspec.json
 
       - name: Deploy using ECS
-        if: inputs.environment == 'dev' || inputs.environment == 'qa'
+        id: ecs-deploy
+        if: inputs.environment == 'dev' || inputs.environment == 'qa' #TODO add prod (or remove the whole if:) when luovutuspalvelu v2 infra is deployed
         uses: aws-actions/amazon-ecs-deploy-task-definition@v2
         with:
           task-definition: ${{ steps.task-def.outputs.task-definition }}
@@ -70,8 +71,21 @@ jobs:
           cluster: koski-cluster
           wait-for-service-stability: true
 
+      - name: Verify ECS deployment
+        id: verify-ecs-deployment
+        if: inputs.environment == 'dev' || inputs.environment == 'qa' #TODO add prod (or remove the whole if:) when luovutuspalvelu v2 infra is deployed
+        run: |
+          CURRENT_TASK_DEF_ARN=$(aws ecs describe-services --cluster koski-cluster --services koski-v2 --query services[0].deployments[0].taskDefinition | jq -r ".")
+          NEW_TASK_DEF_ARN=${{ steps.ecs-deploy.outputs.task-definition-arn }}
+          echo "Current task arn: $CURRENT_TASK_DEF_ARN"
+          echo "New task arn: $NEW_TASK_DEF_ARN"
+          if [ "$CURRENT_TASK_DEF_ARN" != "$NEW_TASK_DEF_ARN" ]; then
+            echo "Deployment failed."
+            exit 1
+          fi
+
       - name: Deploy using CodeDeploy
-        if: inputs.environment == 'prod'
+        if: inputs.environment == 'prod' #TODO remove this step when luovutuspalvelu v2 infra is deployed
         uses: aws-actions/amazon-ecs-deploy-task-definition@v2
         with:
           task-definition: ${{ steps.task-def.outputs.task-definition }}
